- name: Check the Conditions in List 
  hosts: localhost
  become: yes
  tasks:
  - name: Check the user is there not 
    ansible.builtin.command: id hari 
    register: printing_out
    ignore_errors: true
  - name: Check The output
    ansible.builtin.debug:
      msg: "output after trying to get user id {{printing_out}}"
  - name: Checking users exit status
    ansible.builtin.debug:
      msg: "{{printing_out.rc}}"
  - name: Create user with user name hari when users exit status is not equal to 0
    ansible.builtin.user:
      name: hari
    when: printing_out.rc != 0