#Task: To install Nginx in the server and start the server
- name: To install nginx and start the nginx
  hosts: all
  become: yes
  vars:
    name: nginx
    version: latest
  tasks:
  - name: To install Nginx Server
    ansible.builtin.yum:
      name: nginx
      state: latest
  - name: start the service of nginx
    ansible.builtin.service:
      name: nginx
      state: started