- name: Print Varibles in the terminal
  hosts: localhost
  vars:
    course: DevOps
    Trainer: Hari Vardhan
    date: 10-20-25
  tasks:
    - name: Printing The messages in the terminal
      ansible.builtin.debug:
        msg: " I am Learning {{course}} under the trainer {{Trainer}} from date {{date}}"
