- name: Install Mongo db and start the service
  hosts: localhost
  become: yes
  tasks:
  - name: Copy Conf File Src tO destination
    copy: 
      src: mongo.repo
      dest: /etc/yum.repos.d/mongo.repo
  - name: Install The Nginx Service and start
    yum: 
      name: mongodb-org
      state: installed
  - name: Start The service
    service: 
      name: mongod
      state: started
      enabled: yes
  - name: Replace Content using replace module
    replace: 
      path: /etc/mongod.conf
      regexp: '127.0.0.1'
      replace: '0.0.0.0'
  - name: System restart mongodb-org
    service: 
      name: mongod
      state: restarted