- name: Varible Checking
  hosts: localhost
  become: yes
  vars_prompt:
    - name: USERNAME
      prompt: Enter user name
      private: false
    - name: PASSWORD
      prompt: Enter password 
      private: false
    - name: ROLLNO
      prompt: Enter rollno
      private: false
    - name: DOORNO
      prompt: Enter DOORNO
      private: false
  tasks:
    - name: Printing Prompt varibles
      debug:
        msg: "My name {{USERNAME}}, My Password {{PASSWORD}},My RollNo {{ROLLNO}}, My Door no {{DOORNO}}"
