- name: The Data Types
  hosts: localhost
  become: yes
  vars:
  -  name: "Hari Vardhan" # String
  - id: 25 #Number
  - IsTrueCondition: true # Boolean
  - Experience: # Maps
      - aws: 12
      - devops: 12
      - ansible: 15
      - kubernetes: 12
  - address: # List
      - kadapa
      - andhrapradesh
      - tirupathi
  tasks:
  - name: Taking Number from PlayLevel
    ansible.builtin.debug:
      msg: "{{name}}"
  - name: Taking Number from PlayLevel
    ansible.builtin.debug:
      msg: "{{id}}"
  - name: Taking Number from PlayLevel
    ansible.builtin.debug:
      msg: "{{IsTrueCondition}}"
  - name: Taking Number from PlayLevel
    ansible.builtin.debug:
      msg: "{{Experience}}"
  - name: Taking Number from PlayLevel
    ansible.builtin.debug:
      msg: "{{address}}"