- name: All Variables
  hosts: localhost
  become: yes
  vars:
    NAME: "Peddireddy"
    COURSE: "DevOps"
    ID: 12345
  vars_files:
  - Variablefilesall.yaml
  vars_prompt:
  - name: NAME
    prompt: Enter Your Name
    private: false
  tasks:
  - name: Taking the varibles from Vars 
    ansible.builtin.debug:
      msg: "My name {{NAME}}"
  - name: Taking the varibles from var var_files
    ansible.builtin.debug:
      msg: "My Name is {{NAME}}"
  - name: Taking the varibles from var var_files
    ansible.builtin.debug:
      msg: "My Name is {{NAME}}"
  